import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
test('floating panel checks message identity, resizes, minimizes and avoids peer panels',async()=>{
  const listeners={},buttonHandlers={};
  const style=()=>({});
  const panel={hidden:true,style:style(),append(f){this.frame=f;}};
  const button={hidden:false,style:style(),setAttribute(){},focus(){},addEventListener(k,v){buttonHandlers[k]=v;}};
  const root={set innerHTML(v){},querySelector:s=>s==='.panel'?panel:button};
  const host={style:style(),attachShadow:()=>root,remove(){}};
  let peerOpen=false;
  const peer={getBoundingClientRect:()=>({width:52,height:52,right:1264,top:650}),shadowRoot:{querySelector:()=>peerOpen?{getBoundingClientRect:()=>({left:872,bottom:650})}:null}};
  const document={getElementById:id=>id==='xclearreply-widget'?peer:null,querySelectorAll:()=>[],documentElement:{append(){}},addEventListener(k,v){listeners[k]=v;},createElement:t=>t==='iframe'?{contentWindow:{}}:host};
  const window={addEventListener(k,v){listeners[k]=v;}};window.top=window;
  const context={window,document,chrome:{runtime:{id:'extension',getURL:p=>'chrome-extension://extension/'+p.replace(/^\//,'')}},innerWidth:1280,innerHeight:720,URL,setInterval:()=>1,clearInterval(){}};
  vm.createContext(context);vm.runInContext(await readFile(new URL('../src/content/panel.js',import.meta.url),'utf8'),context);
  assert.equal(host.style.bottom,'82px');buttonHandlers.click();assert.equal(panel.hidden,false);
  const resize={source:panel.frame.contentWindow,origin:'chrome-extension://extension',data:{type:'CIRCLEMATE_RESIZE',height:300}};
  listeners.message({...resize,source:{}});assert.notEqual(panel.style.height,'302px');
  listeners.message({...resize,origin:'https://x.com'});assert.notEqual(panel.style.height,'302px');
  listeners.message(resize);assert.equal(panel.style.height,'302px');
  listeners.message({...resize,data:{type:'CIRCLEMATE_RESIZE',height:550}});assert.equal(panel.style.height,'552px');
  assert.equal(host.style.width,'52px');assert.equal(host.style.left,'1212px');
  peer.getBoundingClientRect=()=>({width:56,height:56,left:1200,right:1256,top:600});
  listeners.resize();assert.equal(host.style.width,'56px');assert.equal(host.style.height,'56px');assert.equal(host.style.left,'1200px');assert.equal(host.style.bottom,'132px');
  peerOpen=true;listeners.resize();assert.equal(panel.style.right,'420px');
  context.innerWidth=400;peer.shadowRoot.querySelector=()=>({getBoundingClientRect:()=>({left:8,bottom:650})});listeners.resize();assert.equal(panel.hidden,true);assert.equal(button.disabled,true);
  peer.shadowRoot.querySelector=()=>null;listeners.resize();assert.equal(button.disabled,false);
  buttonHandlers.click();listeners.message({...resize,data:{type:'CIRCLEMATE_MINIMIZE'}});assert.equal(panel.hidden,true);assert.equal(button.hidden,false);
});
