(() => {
  'use strict';
  if(window!==window.top)return;
  const api=globalThis.CircleMate ||= {},observed=new WeakSet();
  let panel=null,generation=0,owner='',timer=null,resizePanel=null;
  const css=`
.cm-post-trigger{margin-top:12px;width:100%;min-height:36px;display:flex;align-items:center;justify-content:center;gap:8px;border:1px solid #cfd9de;border-radius:18px;background:transparent;color:inherit;padding:7px 12px;font:600 13px system-ui;cursor:pointer}.cm-post-trigger svg{width:18px;height:18px;fill:currentColor}.cm-post-trigger:hover{background:#1d9bf012;border-color:#1d9bf0;color:#1d9bf0}
.cm-post-panel{inset:auto;margin:0;position:fixed;z-index:2147483600;box-sizing:border-box;width:520px;max-width:calc(100vw - 24px);max-height:calc(100vh - 24px);display:flex;flex-direction:column;overflow:hidden;border:1px solid #cfd9de;border-radius:18px;background:#fff;color:#0f1419;padding:0;box-shadow:0 12px 40px #0002;font:13px system-ui;--cm-muted:#536471;--cm-line:#cfd9de55}.cm-post-panel:not(:popover-open){display:none}.cm-post-panel[data-dark=true]{--cm-muted:#a0adb8;--cm-line:#53647166}
.cm-post-head{display:flex;align-items:center;gap:4px;flex-shrink:0;padding:14px 12px 10px 16px}.cm-post-title{flex:1;min-width:0}.cm-post-title strong{display:block;font-size:15px;line-height:1.4}.cm-post-title small{display:block;color:var(--cm-muted);font-size:12px;margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.cm-post-panel button{font:inherit;cursor:pointer;color:var(--cm-muted);border:0;background:transparent;border-radius:18px;min-width:34px;min-height:34px;padding:7px;display:inline-flex;align-items:center;justify-content:center;gap:6px;transition:background .15s,color .15s}.cm-post-panel button:hover{background:#1d9bf012;color:#1d9bf0}.cm-post-panel button:disabled{color:var(--cm-muted);cursor:default;opacity:.65}.cm-post-panel svg{width:18px;height:18px;fill:currentColor;flex-shrink:0}.cm-post-panel button:focus-visible,.cm-post-panel a:focus-visible,.cm-post-trigger:focus-visible{outline:2px solid #1d9bf0;outline-offset:2px}.cm-post-list{overflow:auto;overscroll-behavior:contain;min-height:0;scrollbar-width:thin;padding:0 16px 8px}
.cm-post-entry{padding:14px 0 8px;border-top:1px solid var(--cm-line)}.cm-post-text{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.65;margin:8px 0;font-size:14px}.cm-post-date,.cm-post-status{font-size:11px;color:var(--cm-muted);line-height:1.5}.cm-post-status{margin:0;padding:0 16px 12px;flex-shrink:0}.cm-post-status[data-error=true]{color:#d64545}.cm-post-actions{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:8px -7px 0}.cm-post-actions button{min-width:52px;font-size:12px;font-variant-numeric:tabular-nums}.cm-post-actions a{display:inline-flex;align-items:center;justify-content:center;width:34px;height:34px;border-radius:50%;color:var(--cm-muted);text-decoration:none}.cm-post-actions a:hover{color:#1d9bf0;background:#1d9bf012}.cm-post-panel button[data-liked=true],.cm-post-panel button[data-icon=heart]:hover{color:#f91880;background:#f9188010}.cm-post-panel button[data-liked=true] path{d:path('M16.7 3c-1.9 0-3.5.9-4.7 2.4C10.8 3.9 9.2 3 7.3 3 4.4 3 2 5.4 2 8.3c0 4.4 5.4 9.1 10 12.7 4.6-3.6 10-8.3 10-12.7C22 5.4 19.6 3 16.7 3z')}.cm-post-entry small{display:block;color:var(--cm-muted);font-size:11px}.cm-post-more{color:#1d9bf0!important;padding:4px 0!important;min-height:28px!important;font-size:12px!important}.cm-post-panel button[data-busy=true] svg{animation:cm-post-spin 1s linear infinite}@keyframes cm-post-spin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.cm-post-panel button{transition:none}.cm-post-panel button[data-busy=true] svg{animation:none}}`;
  const replyCss=`.cm-inline-reply{margin:10px 0 4px;padding:12px;background:#1d9bf008;border:1px solid var(--cm-line);border-radius:12px}.cm-inline-reply label{display:block;color:var(--cm-muted);font-size:12px}.cm-inline-reply textarea{display:block;box-sizing:border-box;width:100%;margin-top:8px;padding:10px;border:1px solid var(--cm-line);border-radius:10px;resize:vertical;min-height:94px;max-height:220px;font:14px/1.6 system-ui;background:transparent;color:inherit}.cm-inline-reply textarea:focus{outline:2px solid #1d9bf0;outline-offset:1px}.cm-inline-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap;margin-top:10px}.cm-post-panel .cm-inline-send{background:#1d9bf0;color:#fff;font-weight:600;padding:7px 14px}.cm-post-panel .cm-inline-send:disabled{background:#1d9bf020;color:var(--cm-muted);opacity:1}.cm-inline-status{font-size:12px;line-height:1.5;color:var(--cm-muted);margin:8px 0}.cm-inline-status:empty{display:none}`;
  const paths={posts:'M4 3h16v18H4V3zm2 2v14h12V5H6zm2 3h8v2H8V8zm0 4h8v2H8v-2z',external:'M14 3h7v7h-2V6.4l-9.3 9.3-1.4-1.4L17.6 5H14V3zM5 5h6v2H5v12h12v-6h2v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2z',heart:'M16.7 3c-1.9 0-3.5.9-4.7 2.4C10.8 3.9 9.2 3 7.3 3 4.4 3 2 5.4 2 8.3c0 4.4 5.4 9.1 10 12.7 4.6-3.6 10-8.3 10-12.7C22 5.4 19.6 3 16.7 3zm-4.7 15.5c-4.6-3.7-8-7.2-8-10.2C4 6.5 5.5 5 7.3 5c1.6 0 3 1.1 3.8 2.6l.9 1.6.9-1.6C13.7 6.1 15.1 5 16.7 5 18.5 5 20 6.5 20 8.3c0 3-3.4 6.5-8 10.2z',reply:'M12 2a10 10 0 0 0-7 17.1L3 22l5.2-1.9A10 10 0 1 0 12 2zm0 2a8 8 0 1 1-3.6 15.1l-.4-.2-1.5.5.6-1.1-.6-.5A8 8 0 0 1 12 4z',refresh:'M19 7V2l-2 2a9 9 0 1 0 3.5 9h-2A7 7 0 1 1 15.5 5L13 7h6z',close:'M6 4.6 12 10.6l6-6 1.4 1.4-6 6 6 6-1.4 1.4-6-6-6 6L4.6 18l6-6-6-6z'};
  function style(root){if(root.querySelector('[data-cm-post-style]'))return;const s=document.createElement('style');s.dataset.cmPostStyle='1';s.textContent=css+replyCss;(root===document?document.head:root).append(s);}
  function account(){try{const raw=document.cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith('twid='))?.slice(5);return decodeURIComponent(raw||'').replace(/^u=/,'').replace(/"/g,'');}catch{return '';}}
  function group(){return location.pathname.match(/^\/i\/chat\/(g\d+)\/info\/?$/)?.[1]||'';}
  function close(){generation++;panel?.remove();panel=null;owner='';resizePanel=null;}
  function icon(name,label){const b=document.createElement('button');b.type='button';b.dataset.icon=name;b.title=label;b.setAttribute('aria-label',label);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',paths[name]);svg.append(p);b.append(svg);return b;}
  function profileName(card){for(const a of card.querySelectorAll('a[href]')){try{const url=new URL(a.href,location.origin);const match=url.pathname.match(/^\/([a-z0-9_]{1,15})\/?$/i);if(url.origin===location.origin&&match)return match[1].toLowerCase();}catch{}}return '';}
  function open(card,username){
    close();const accountId=account(),groupId=group();if(!/^\d{1,30}$/.test(accountId)||!groupId)return;
    owner=accountId;const token=generation,expandedPosts=new Set();let activeReply=null;style(document);
    panel=document.createElement('section');panel.className='cm-post-panel';panel.setAttribute('popover','manual');panel.setAttribute('role','dialog');panel.setAttribute('aria-label',`@${username} 最近帖子`);panel.tabIndex=-1;
    const paint=getComputedStyle(card.querySelector('[data-base-ui-focusable]')||card);panel.style.background=paint.backgroundColor;panel.style.color=paint.color;const rgb=paint.color.match(/\d+/g);panel.dataset.dark=String(rgb&&Number(rgb[0])>160);
    const rect=card.getBoundingClientRect();
    const head=document.createElement('div');head.className='cm-post-head';const heading=document.createElement('div');heading.className='cm-post-title';const title=document.createElement('strong');title.textContent='最近帖子';const member=document.createElement('small');member.textContent=`@${username}`;heading.append(title,member);
    const refresh=icon('refresh','刷新最近帖子'),exit=icon('close','关闭最近帖子');exit.onclick=close;head.append(heading,refresh,exit);
    const status=document.createElement('p');status.className='cm-post-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');
    const list=document.createElement('div');list.className='cm-post-list';panel.append(head,status,list);const surface=card.getRootNode();style(surface);const container=[...surface.querySelectorAll('[role=dialog][data-open]')].at(-1)||document.body;container.append(panel);panel.showPopover();panel.focus();
    function fit(){if(!panel||generation!==token)return;const box=panel.getBoundingClientRect(),margin=16,gap=16;const anchor=container===document.body?rect:container.getBoundingClientRect();let left;if(anchor.right+gap+box.width<=innerWidth-margin)left=anchor.right+gap;else if(anchor.left-gap-box.width>=margin)left=anchor.left-gap-box.width;else left=(innerWidth-box.width)/2;panel.style.left=Math.max(12,Math.min(left,innerWidth-box.width-12))+'px';panel.style.top=Math.max(12,Math.min(Math.max(32,anchor.top),innerHeight-box.height-12))+'px';}
    resizePanel=fit;
    const valid=()=>panel&&panel.isConnected&&generation===token&&account()===accountId&&group()===groupId;
    const notify=(text,error=false)=>{if(valid()){status.textContent=text;status.dataset.error=String(error);}};
    const send=extra=>chrome.runtime.sendMessage({groupId,accountId,username,...extra});
    function render(data){if(!valid())return;const scroll=list.scrollTop;list.replaceChildren();if(!data.posts.length){notify('暂无可读取的公开帖子');return;}notify('原创 / 引用 · '+Math.min(3,data.posts.length)+' 条 · '+new Date(data.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})+' 更新');
      for(const post of data.posts.slice(0,3)){
        const row=document.createElement('article');row.className='cm-post-entry';const time=document.createElement('time');time.className='cm-post-date';time.dateTime=new Date(post.createdAt).toISOString();time.title=new Date(post.createdAt).toLocaleString();time.textContent=new Date(post.createdAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
        const text=document.createElement('p');text.className='cm-post-text';text.textContent=post.text||'此帖包含媒体或文章，请查看原帖';
        row.append(time,text);if(post.text.length>240){const full=post.text;let expanded=expandedPosts.has(post.id);const more=document.createElement('button');more.type='button';more.className='cm-post-more';text.textContent=expanded?full:full.slice(0,240)+'…';more.textContent=expanded?'收起':'展开全文';more.setAttribute('aria-expanded',String(expanded));more.onclick=()=>{expanded=!expanded;if(expanded)expandedPosts.add(post.id);else expandedPosts.delete(post.id);text.textContent=expanded?full:full.slice(0,240)+'…';more.textContent=expanded?'收起':'展开全文';more.setAttribute('aria-expanded',String(expanded));fit();};row.append(more);}if(post.hasMedia){const hint=document.createElement('small');hint.textContent='含图片或视频';row.append(hint);}
        const actions=document.createElement('div');actions.className='cm-post-actions';const like=icon('heart',post.liked?'取消点赞':'点赞'),reply=icon('reply','回复');
        const likes=document.createElement('span');likes.textContent=post.likes==null?'—':String(post.likes);like.append(likes);like.dataset.liked=String(post.liked===true);like.setAttribute('aria-pressed',String(post.liked===true));like.disabled=post.liked==null||post.limited||post.unconfirmed;
        if(post.unconfirmed)like.title='上次结果未确认，请刷新核验';
        const replies=document.createElement('span');replies.textContent=post.replies==null?'—':String(post.replies);reply.append(replies);
        like.onclick=async event=>{if(!event.isTrusted||!valid())return;like.disabled=true;like.setAttribute('aria-busy','true');refresh.disabled=true;notify('正在核验点赞状态…');try{const result=await send({action:'POSTS_LIKE',tweetId:post.id,liked:!post.liked});if(!result?.ok)throw new Error(result?.error||'点赞失败');render(result);list.querySelectorAll('article')[data.posts.findIndex(p=>p.id===post.id)]?.querySelector('[data-icon=heart]')?.focus({preventScroll:true});}catch(e){notify(e.message,true);}finally{if(valid())refresh.disabled=false;}};
        reply.onclick=event=>{if(!event.isTrusted||!valid())return;if(activeReply?.id===post.id){activeReply.view.focus();return;}activeReply?.view.element.remove();const view=api.createInlineReply({accountId,tweetId:post.id,username,onClose:()=>{view.element.remove();activeReply=null;reply.focus({preventScroll:true});fit();},onSend:async(text,requestToken)=>{if(!valid())throw Object.assign(new Error('账号或群列表已切换'),{code:'WRITE_NOT_SENT'});const result=await send({action:'POSTS_REPLY',tweetId:post.id,text,token:requestToken});if(!result?.ok)throw Object.assign(new Error(result?.error||'回复失败'),{code:result?.code});return result;}});activeReply={id:post.id,view};row.append(view.element);fit();view.element.scrollIntoView({block:'nearest'});view.focus();};
        const original=document.createElement('a');original.href=post.url;original.title='查看原帖（新标签页）';original.setAttribute('aria-label','查看原帖（新标签页）');original.append(icon('external','查看原帖').firstElementChild);original.target='_blank';original.rel='noopener noreferrer';actions.append(reply,like,original);row.append(actions);if(activeReply?.id===post.id)row.append(activeReply.view.element);list.append(row);
      }
      list.scrollTop=scroll;fit();
    }
    async function load(force=false){if(!valid())return;refresh.disabled=true;refresh.dataset.busy='true';panel.setAttribute('aria-busy','true');notify(force?'正在刷新…':'正在读取最近帖子…');try{const result=await send({action:'POSTS_READ',refresh:force});if(!result?.ok)throw new Error(result?.error||'读取失败');render(result);}catch(e){notify(e.message,true);}finally{if(valid()){refresh.disabled=false;refresh.dataset.busy='false';panel.setAttribute('aria-busy','false');fit();}}}
    refresh.onclick=()=>void load(true);fit();void load();
  }
  function scan(){
    if(!group()){close();return;}if(panel&&(!panel.isConnected||account()!==owner))close();
    for(const root of api.rosterRoots?.()||[document]){
      if(root===document)continue;
      if(!observed.has(root)){observed.add(root);new MutationObserver(schedule).observe(root,{childList:true,subtree:true,attributes:true,attributeFilter:['data-open']});}
      for(const card of root.querySelectorAll('[role="presentation"][data-open][data-side]')){
        if(!card.querySelector('[data-base-ui-focusable]'))continue;const username=profileName(card),existing=card.querySelector('.cm-post-trigger');if(!username){existing?.remove();continue;}if(existing)continue;
        style(root);const b=icon('posts','查看最近帖子');b.className='cm-post-trigger';const label=document.createElement('span');label.textContent='最近帖子';b.append(label);b.onclick=e=>{e.preventDefault();e.stopPropagation();const current=profileName(card);if(e.isTrusted&&current)open(card,current);};card.querySelector('[data-base-ui-focusable]').append(b);
      }
    }
  }
  function schedule(){clearTimeout(timer);timer=setTimeout(scan,100);}
  new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});
  setInterval(scan,1000);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel&&(panel.contains(panel.getRootNode().activeElement||document.activeElement)||document.activeElement===document.body)){e.preventDefault();close();}});
  window.addEventListener('resize',()=>resizePanel?.(),{passive:true});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden&&panel&&account()!==owner)close();});scan();
})();
