// Sample roster only; actual integration scripts, no X requests or credentials.
import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';
const html=`<!doctype html><html lang="zh"><meta charset="utf-8"><style>body{background:#eee;font:15px system-ui;margin:40px}#embed{max-width:640px;margin:auto;background:#fff;border-radius:24px;overflow:auto;max-height:500px;padding:20px}</style><div id="embed"></div><script>
const root=document.querySelector('#embed').attachShadow({mode:'open'});root.innerHTML='<style>#rows{min-height:900px}.row{display:flex;align-items:center;gap:14px;padding:18px;border-bottom:1px solid #eee}.row a{flex:1;color:#172b34;text-decoration:none}h2{text-align:center}input{margin:12px;padding:12px;border-radius:20px;border:1px solid #ddd;width:90%}</style><h2>所有成员</h2><input placeholder="搜索参与者"><div id="rows">'+['alice','bob','carol','dave'].map((u,i)=>'<div class="row"><a href="https://x.com/'+u+'">'+['小林的创作笔记','海边读书人','阿青','陈墨'][i]+' <small>@'+u+'</small></a><button aria-label="更多 '+u+' 的选项">···</button></div>').join('')+'</div>';
const state={accountId:'1',groups:[{id:'g123',usernames:['alice','bob','carol','dave'],failedReferences:{dave:{}},users:[{id:'2',username:'alice',following:false,blueVerified:true},{id:'3',username:'bob',following:true,followedBy:false,blueVerified:true},{id:'4',username:'carol',following:false},{id:'5',username:'dave',following:null}]}]};const calls=[];
state.memberInteractions={members:{'2':{likes:3,replies:1}},status:'idle',updatedAt:Date.now(),partial:true};
window.chrome={runtime:{sendMessage:async m=>{calls.push(m);if(m.action==='ROSTER_STATE')await new Promise(resolve=>setTimeout(resolve,Number(${Number(process.env.CIRCLEMATE_ROSTER_DELAY || 0)})));if(m.action==='FRAME_CONTEXT')return{isInfo:true,groupId:'g123'};if(m.action==='ROSTER_FOLLOW')state.groups[0].users.find(u=>u.id===m.userId).following=true;if(m.action==='ROSTER_ENRICH')state.groups[0].users[3].following=false;return {ok:true,state:structuredClone(state)};}}};
</script><script src="/shared/roster.js"></script><script src="/content/roster-ui.js"></script></html>`;
createServer(async(req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}if(!['/shared/roster.js','/content/roster-ui.js'].includes(req.url)){res.writeHead(404).end();return;}res.setHeader('Content-Type','text/javascript');res.end(await readFile(new URL('../src'+req.url,import.meta.url)));}).listen(4179,'127.0.0.1',()=>console.log('Roster preview: http://127.0.0.1:4179'));
